// flow-typed signature: 19659abac4bc482713aec12ab6cef7e4
// flow-typed version: <<STUB>>/eslint-config-arista_v0.2.22/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-arista'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-arista' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-arista/index' {
  declare module.exports: $Exports<'eslint-config-arista'>;
}
declare module 'eslint-config-arista/index.js' {
  declare module.exports: $Exports<'eslint-config-arista'>;
}
