// flow-typed signature: 93d3309e655adb2d9fd61b8b4226502b
// flow-typed version: <<STUB>>/int64-buffer_v^0.99.1007/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'int64-buffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'int64-buffer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'int64-buffer/dist/int64-buffer.min' {
  declare module.exports: any;
}

declare module 'int64-buffer/int64-buffer' {
  declare module.exports: any;
}

declare module 'int64-buffer/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'int64-buffer/dist/int64-buffer.min.js' {
  declare module.exports: $Exports<'int64-buffer/dist/int64-buffer.min'>;
}
declare module 'int64-buffer/int64-buffer.js' {
  declare module.exports: $Exports<'int64-buffer/int64-buffer'>;
}
declare module 'int64-buffer/test/test.js' {
  declare module.exports: $Exports<'int64-buffer/test/test'>;
}
