// flow-typed signature: 8fc18b0eda6db07dd77aebe63df589d5
// flow-typed version: <<STUB>>/jsbi_v2.0.5/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsbi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsbi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsbi/dist/jsbi-cjs' {
  declare module.exports: any;
}

declare module 'jsbi/dist/jsbi-umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsbi/dist/jsbi-cjs.js' {
  declare module.exports: $Exports<'jsbi/dist/jsbi-cjs'>;
}
declare module 'jsbi/dist/jsbi-umd.js' {
  declare module.exports: $Exports<'jsbi/dist/jsbi-umd'>;
}
