// flow-typed signature: a9c0d2ad5823ef239d17696063eea744
// flow-typed version: <<STUB>>/json-bignumber_v1.0.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-bignumber'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-bignumber' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json-bignumber/dist/JSONBigNumber.min' {
  declare module.exports: any;
}

declare module 'json-bignumber/karma.conf' {
  declare module.exports: any;
}

declare module 'json-bignumber/src/JSONBigNumber' {
  declare module.exports: any;
}

declare module 'json-bignumber/test/JSONBigNumber.performance.spec' {
  declare module.exports: any;
}

declare module 'json-bignumber/test/JSONBigNumber.spec' {
  declare module.exports: any;
}

declare module 'json-bignumber/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json-bignumber/dist/JSONBigNumber.min.js' {
  declare module.exports: $Exports<'json-bignumber/dist/JSONBigNumber.min'>;
}
declare module 'json-bignumber/karma.conf.js' {
  declare module.exports: $Exports<'json-bignumber/karma.conf'>;
}
declare module 'json-bignumber/src/JSONBigNumber.js' {
  declare module.exports: $Exports<'json-bignumber/src/JSONBigNumber'>;
}
declare module 'json-bignumber/test/JSONBigNumber.performance.spec.js' {
  declare module.exports: $Exports<'json-bignumber/test/JSONBigNumber.performance.spec'>;
}
declare module 'json-bignumber/test/JSONBigNumber.spec.js' {
  declare module.exports: $Exports<'json-bignumber/test/JSONBigNumber.spec'>;
}
declare module 'json-bignumber/webpack.config.js' {
  declare module.exports: $Exports<'json-bignumber/webpack.config'>;
}
