// flow-typed signature: 9bc4d7ecf4e8de596c9191fc1e521dc6
// flow-typed version: <<STUB>>/mock-socket_v8.0.5/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mock-socket'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mock-socket' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mock-socket/dist/mock-socket.amd' {
  declare module.exports: any;
}

declare module 'mock-socket/dist/mock-socket.cjs' {
  declare module.exports: any;
}

declare module 'mock-socket/dist/mock-socket.es' {
  declare module.exports: any;
}

declare module 'mock-socket/dist/mock-socket' {
  declare module.exports: any;
}

declare module 'mock-socket/src/algorithms/close' {
  declare module.exports: any;
}

declare module 'mock-socket/src/constants' {
  declare module.exports: any;
}

declare module 'mock-socket/src/event/close' {
  declare module.exports: any;
}

declare module 'mock-socket/src/event/event' {
  declare module.exports: any;
}

declare module 'mock-socket/src/event/factory' {
  declare module.exports: any;
}

declare module 'mock-socket/src/event/message' {
  declare module.exports: any;
}

declare module 'mock-socket/src/event/prototype' {
  declare module.exports: any;
}

declare module 'mock-socket/src/event/target' {
  declare module.exports: any;
}

declare module 'mock-socket/src/helpers/array-helpers' {
  declare module.exports: any;
}

declare module 'mock-socket/src/helpers/byte-length' {
  declare module.exports: any;
}

declare module 'mock-socket/src/helpers/dedupe' {
  declare module.exports: any;
}

declare module 'mock-socket/src/helpers/delay' {
  declare module.exports: any;
}

declare module 'mock-socket/src/helpers/global-object' {
  declare module.exports: any;
}

declare module 'mock-socket/src/helpers/logger' {
  declare module.exports: any;
}

declare module 'mock-socket/src/helpers/normalize-send' {
  declare module.exports: any;
}

declare module 'mock-socket/src/helpers/protocol-verification' {
  declare module.exports: any;
}

declare module 'mock-socket/src/helpers/proxy-factory' {
  declare module.exports: any;
}

declare module 'mock-socket/src/helpers/url-verification' {
  declare module.exports: any;
}

declare module 'mock-socket/src/index' {
  declare module.exports: any;
}

declare module 'mock-socket/src/network-bridge' {
  declare module.exports: any;
}

declare module 'mock-socket/src/server' {
  declare module.exports: any;
}

declare module 'mock-socket/src/socket-io' {
  declare module.exports: any;
}

declare module 'mock-socket/src/websocket' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mock-socket/dist/mock-socket.amd.js' {
  declare module.exports: $Exports<'mock-socket/dist/mock-socket.amd'>;
}
declare module 'mock-socket/dist/mock-socket.cjs.js' {
  declare module.exports: $Exports<'mock-socket/dist/mock-socket.cjs'>;
}
declare module 'mock-socket/dist/mock-socket.es.js' {
  declare module.exports: $Exports<'mock-socket/dist/mock-socket.es'>;
}
declare module 'mock-socket/dist/mock-socket.js' {
  declare module.exports: $Exports<'mock-socket/dist/mock-socket'>;
}
declare module 'mock-socket/src/algorithms/close.js' {
  declare module.exports: $Exports<'mock-socket/src/algorithms/close'>;
}
declare module 'mock-socket/src/constants.js' {
  declare module.exports: $Exports<'mock-socket/src/constants'>;
}
declare module 'mock-socket/src/event/close.js' {
  declare module.exports: $Exports<'mock-socket/src/event/close'>;
}
declare module 'mock-socket/src/event/event.js' {
  declare module.exports: $Exports<'mock-socket/src/event/event'>;
}
declare module 'mock-socket/src/event/factory.js' {
  declare module.exports: $Exports<'mock-socket/src/event/factory'>;
}
declare module 'mock-socket/src/event/message.js' {
  declare module.exports: $Exports<'mock-socket/src/event/message'>;
}
declare module 'mock-socket/src/event/prototype.js' {
  declare module.exports: $Exports<'mock-socket/src/event/prototype'>;
}
declare module 'mock-socket/src/event/target.js' {
  declare module.exports: $Exports<'mock-socket/src/event/target'>;
}
declare module 'mock-socket/src/helpers/array-helpers.js' {
  declare module.exports: $Exports<'mock-socket/src/helpers/array-helpers'>;
}
declare module 'mock-socket/src/helpers/byte-length.js' {
  declare module.exports: $Exports<'mock-socket/src/helpers/byte-length'>;
}
declare module 'mock-socket/src/helpers/dedupe.js' {
  declare module.exports: $Exports<'mock-socket/src/helpers/dedupe'>;
}
declare module 'mock-socket/src/helpers/delay.js' {
  declare module.exports: $Exports<'mock-socket/src/helpers/delay'>;
}
declare module 'mock-socket/src/helpers/global-object.js' {
  declare module.exports: $Exports<'mock-socket/src/helpers/global-object'>;
}
declare module 'mock-socket/src/helpers/logger.js' {
  declare module.exports: $Exports<'mock-socket/src/helpers/logger'>;
}
declare module 'mock-socket/src/helpers/normalize-send.js' {
  declare module.exports: $Exports<'mock-socket/src/helpers/normalize-send'>;
}
declare module 'mock-socket/src/helpers/protocol-verification.js' {
  declare module.exports: $Exports<'mock-socket/src/helpers/protocol-verification'>;
}
declare module 'mock-socket/src/helpers/proxy-factory.js' {
  declare module.exports: $Exports<'mock-socket/src/helpers/proxy-factory'>;
}
declare module 'mock-socket/src/helpers/url-verification.js' {
  declare module.exports: $Exports<'mock-socket/src/helpers/url-verification'>;
}
declare module 'mock-socket/src/index.js' {
  declare module.exports: $Exports<'mock-socket/src/index'>;
}
declare module 'mock-socket/src/network-bridge.js' {
  declare module.exports: $Exports<'mock-socket/src/network-bridge'>;
}
declare module 'mock-socket/src/server.js' {
  declare module.exports: $Exports<'mock-socket/src/server'>;
}
declare module 'mock-socket/src/socket-io.js' {
  declare module.exports: $Exports<'mock-socket/src/socket-io'>;
}
declare module 'mock-socket/src/websocket.js' {
  declare module.exports: $Exports<'mock-socket/src/websocket'>;
}
